### ISSUE TITLE
Python script that searches PyLith parameter files

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#237]
Create a Python script `pylith_cfgsearch` that searches .cfg files for the `metadata` section and dumps a summary of search results. The default would be to return all simulations with optional arguments to restrict by keywords and/or features.

```
pylith_cfgsearch [--keywords] [--features] [--path=SEARCH_PATH] [--display=description,keywords,features]
```

Default output would be (with summary information limited by `--display`)
```
PATH_TO_CFG_FILE  summary.description  summary.keywords  summary.features
```

Use `pathlib.glob` to get list of `.cfg` files in `SEARCH-PATH`.

Relies on PyLithApp.metadata; see #229

**Comment by baagaard-usgs** [comment]
Work in progress: https://github.com/geodynamics/pylith/tree/baagaard/feature-simulation-metadata

**Comment by baagaard-usgs** [comment]
# TODO

- [X] Handle cases with missing metadata
- [ ] Add simulation metadata for examples
- [ ] Add simulation metadata for full-scale tests
- [ ] Update `SimulationMetadata` to require description, pylith_version, arguments
