### ISSUE TITLE
Set pointwise functions using weak form instead of PetscDS

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#267]
# Todo

- [x] Replace use of `PetscDSSetResidual()` with `PetscWeakFormSetIndexResidual()`
- [x] Use weak form keys with correct labels and values in computing residuals and Jacobians
- [x] Update `IntegratorInterface` to always use integration patches so labels/values of adjacent faces are valid.

**Comment by baagaard-usgs** [comment]
Partially implemented in #269
