### ISSUE TITLE
Importing mesh files from Gmsh

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#32]
Implement a mesh importer for the MED file format for meshes generated by Gmsh and Salome.

This would include determining how MED identifies groups of vertices and cell faces for boundary conditions and interfaces, and how cells are marked for different material types.

Ideally, this would include developing the scripts to generate MED files for each of the examples (or the most widely used examples.

## Level of difficulty
Easy to moderate.

**Comment by baagaard-usgs** [comment]
PETSc can read a (small) variety of mesh formats, including Gmsh via [DMPlexCreateFromFile](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DMPLEX/DMPlexCreateFromFile.html). We need to implement a mesh importer that is a wrapper around `DMPlexCreateFromFile()`.

Notes:
1. See [DMPlexCreateGmsh](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DMPLEX/DMPlexCreateGmsh.html#DMPlexCreateGmsh) for details on how PETSc creates a `DMPlex` object from the Gmsh file.
2. If we want to use names to label boundary conditions, etc then we need to make use of `$PhysicalNames` in Gmsh. See [Gmsh format information](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format). PETSc does not yet support use of `$PhysicalNames`.

**Comment by baagaard-usgs** [comment]
@knepley Here is the Gmsh test case
https://github.com/geodynamics/pylith/commit/716f8cbf02aae21e0bdca189eedc675d918dbca3

If we have to move to supporting side sets, we can go that route.

**Comment by knepley** [comment]
@baagaard-usgs I pushed a small change to your script and now `knepley/pylith` makes meshes that I think should work in PyLith.

**Comment by knepley** [comment]
Also, I found this tutorial http://jsdokken.com/converted_files/tutorial_gmsh.html

**Comment by baagaard-usgs** [comment]
The MMS elasticity tests works with the Gmsh generated mesh. I think the next step is to create a suite of unit tests comparable to the CUBIT/Exodus II tests. I will try to do that over the next week or so.

**Comment by knepley** [comment]
I agree. I think I understand their system now. It should not be hard for us to get going.

**Comment by baagaard-usgs** [comment]
# TODO

- [ ] Implement unit tests
- [ ] Use Gmsh in _some_ MMS tests
- [ ] Use Gmsh in _some_ full-scale tests
- [ ] Provide Gmsh for `examples/2d/box`
- [ ] Provide Gmsh for `examples/3d/box`
- [ ] Provide Gmsh for `examples/2d/reverse`
- [ ] Provide Gmsh for `examples/2d/strikeslip`
- [ ] Provide Gmsh for `examples/2d/subduction`

**Comment by baagaard-usgs** [comment]
@knepley There is a problem with the Gmsh importing. You assumed that you can associated multiple values with a named physical group (`material-id`). It looks to me like there is a one to one relationship between a tag and the name. In other words, each physical group can have only one tag value and one name; you can't associate multiple values with a name. This means that assigning the name `material-id` to a physical group only works when we have 1 material. If we have 2 materials and you attempt to assign the name `material-id` to multiple physical groups, the name is used only for the last physical group named.

I see a couple of options:

1. Change the PyLith code so that the user can assign the label name and label value to be used for materials instead of requiring the label name to be `material-id`. This will require updating some other parts of the code, because there are places (refinement? creating cohesive cells?) where you use the `material-id` label to do other things (fixing this may just require defining a separate label for the operation you want to do).
2. Come up with a scheme to assign `material-id` label values to the different physical groups in Gmsh.

Option #1 seems like the best solution to me.

**Comment by baagaard-usgs** [comment]
Matt's solution is to use `material-id:TAG`. This produces unique names. The importer now ignores everything after the `:`.

**Comment by baagaard-usgs** [comment]
## Description

@knepley In setting up tests for reading Gmsh files, I found a related issue. The PETSc Gmesh reader sets the label values to the tag. As a result, the label values for my boundaries are not the usual 1, but whatever the tag is. Because we create a different label for each physical name, it seems like we should be able to set the label value to 1. I don't know if doing this would break other people's use of Gmsh.  

For my new test case, I am also not getting all of the vertices in the label. I get all of the edges. In some cases, I get just the vertices on the ends and other times no vertices at all (just the edges).

## Reproduce

**PETSc branch**: `knepley/pylith`
**PyLith branch**: `baagaard/feature-gmsh-example`

1. Build
2. `make check -C tests/libtests/meshio`
3. .libs/test_meshio --tests=pylith::meshio::TestMeshIOPetsc_GmshTri_Ascii --journal.debug=TestMeshIOPetsc

```
-- snip --
Label 'boundary_yneg': [these are edges, missing vertices; expect 5 vertices]
[0]: 71 (6)
[0]: 76 (6)
[0]: 111 (6)
[0]: 116 (6)
Label 'boundary_xpos': [first two are vertices, rest are edges; expect 5 vertices]
[0]: 38 (5)
[0]: 39 (5)
[0]: 107 (5)
[0]: 114 (5)
[0]: 122 (5)
[0]: 124 (5)
Label 'boundary_ypos': [these are edges, missing vertices; expect 5 vertices]
[0]: 80 (7)
[0]: 85 (7)
[0]: 103 (7)
[0]: 106 (7)
Label 'boundary_xneg': [first two are vertices, rest are edges; expect 5 vertices]
[0]: 36 (4)
[0]: 41 (4)
[0]: 73 (4)
[0]: 83 (4)
[0]: 87 (4)
[0]: 95 (4)
Label 'fault': [first two are vertices, rest are edges; expect 5 vertices]
[0]: 37 (3)
[0]: 40 (3)
[0]: 69 (3)
[0]: 77 (3)
[0]: 88 (3)
[0]: 94 (3)
 : assertion

!!!FAILURES!!!
Test Results:
Run:  4   Failures: 1   Errors: 0


1) test: pylith::meshio::TestMeshIOPetsc_GmshTri_Ascii::testRead (F) line: 274 /Users/baagaard/src/cig/pylith/tests/libtests/meshio/TestMeshIO.cc
assertion failed
- Expression: numPoints > 0 [We assume the label value is 1 when we try to get the points for the label. The label value is equal to the tag, which is not 1, so we don't get any points.]
```

**Comment by baagaard-usgs** [comment]
## Useful Gmsh tutorials

* `tutorials/python/t6.py` Transfinite mesh
* `tutorials/python/t15.py` Embedded geometry
* `tutorials/python/t16.py` OpenCascade example
* `tutorials/python/x2.py` Create mesh conforming to terrain directly

**Comment by baagaard-usgs** [comment]
@knepley Once you add the 3 patches I sent you to PETSc, I think I have Gmsh working for all of our use cases. I have added use of Gmsh to libtests, several mmstests, some full-scale tests, and the strikeslip-2d, reverse-2d, and subduction-2d examples.
