### ISSUE TITLE
Reimplement static Green's functions

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#393]
## Description

Reimplement static Green's functions in v3 code base.

## TODO

- [x] Use same user-interface as v2.2.2 (specify slip components, threshold)
- [x] Add libtests for `ProgressMonitorStep`
- [x] Implement full-scale test
