### ISSUE TITLE
Reorganize examples and tests directories

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#410]
## Description

There are inconsistencies in the layout of the `examples`, `tests/mmstests`, and `tests/fullscale` directories.

## Desired Solution

* Flatten the `examples` directories (append `2d` and `3d` to example name and eliminate those directories)
* Rename `elasticity` to `linearelasticity` in `mmstests`
* Separate incompressible elasticity full-scale tests into separate directory

Implementing in branch `baagaard/reorganize-examples-tests`

**Comment by baagaard-usgs** [comment]
## TODO

- [ ] Reorganize examples source code
- [ ] Reorganize tests source code
- [ ] Move `docs-sphinx` to `docs`
- [ ] Update user manual for new examples layout
