### ISSUE TITLE
Bug in using multiple faults

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#443]
## Describe the bug

The integration keys for the kernels (pointwise functions) for the negative and positive fault faces don't include anything to associate them with the fault. As a result, they get applied to multiple faults.

## Proposed solution

Update the integration `part` to include the equation part, fault label value, and face (negative, positive, fault).

## TODO

- [x] Migrate changes from branch `baagaard/feature-prescribed-slip-dynamic-new`
- [x] Update integration key to use fault label value
- [x] Add MMS test with two faults (shear with no slip)
- [x] Add full-scale test with two faults (three rigid blocks; shear with no slip)
