### ISSUE TITLE
Add solver defaults for various types of problems

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#444]
## Description

The optimum preconditioner and solver settings depend on the system of equations (governing equation, presence of faults, running in parallel, etc). Users often forget or struggle to adjust these settings.

## Desired Solution

Provide default PETSc settings that work for most situations. These should be set _before_ calls `TSSetFromOptions()` or `SNESSetFromOptions` (`MMSTest`, `GreenFns`).

## TODO

- [x] Create C++ `PetscDefaults` class with static method for setting default PETSc settings.
- [x] Use journal::info to display settings
- [x] Update full-scale tests
- [x] Override default solver options in incompressible elasticity MMS tests (tolerances?)
- [x] Update examples
- [x] Add to documentation
