### ISSUE TITLE
PyLith v3.1.0 documentation TODO

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#479]
- [ ] Examples: Add physics and physics -> parameter information
- [ ] Add troubleshooting-2d to manual
- [ ] Mathematic explanation of preconditioners
- [ ]
