### ISSUE TITLE
Parallel mesh input

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#53]
Support parallel mesh reading using MED format.

Preprocessing to convert to MED format from many other formats can be done using https://github.com/nschloe/meshio.

**Comment by knepley** [comment]
@baagaard-usgs We are not supporting MED anymore. It looks like it was dropped. We have parallel input from HDF5. I think we just write a small converter from any format we are using to HDF5. This should be easy since it would just be a DMLoad()/DMView() and could be done from Python.

**Comment by baagaard-usgs** [comment]
Parallel mesh loading requires generating cohesive cells in parallel! I think this is the main obstacle.

**Comment by baagaard-usgs** [comment]
- [ ] Allow specification of boundary conditions using faces rather than just vertices
- [ ] Load mesh in serial, distribute, and then adjust topology in parallel
- [ ] Load mesh in serial + distribute or load in parallel and then adjust topology in parallel

**Comment by baagaard-usgs** [comment]
## Notes on implementation 

1. Do **not** call `DMLabelComplete()` before calling `pylith::faults::TopologyOps::updateCohesiveLabel()`.
2. Need to set `material-id` for cohesive cells.

**Comment by baagaard-usgs** [comment]
# Update converter

- [ ] Add ability to reorder mesh

# Refactor `MeshGenerator` and `MeshImporter`

## Features

- `MeshInitializer` to capture phases of mesh initialization
- Initialization is done in modular phases
  - Read mesh
  - Reorder mesh
  - Distribute mesh
  - Refine mesh
  - Extrude transform to create cohesive cells
- Use a switch for serial vs parallel loading
- Allow conversion to parallel input with reordering as possible phases
- `MeshIOPetsc` contains a call to `DMPlexDistributeSetDefault()` to turn off automatic distribution (still need to redistribute to get a good partition).

## Tasks

- [x] Implement `MeshInitializer` with default phases
- [x] Implement abstract base class `MeshInitializerPhase`
- [x] Implement `MeshReader` using `MeshIO`
- [x] Implement `MeshWriter` using `MeshIO`
- [x] Implement `MeshReordering`
- [x] Implement `MeshDistributor`
- [x] Implement `MeshRefiner`
- [x] Implement `MeshInsertInterfaces`

**Comment by baagaard-usgs** [comment]
- [x] Clean up code, removing debugging
- [x] Remove old method of creating faults
- [ ] Add convert step to gmsh_utils.GenerateMeshApp().
- [ ] Update examples
- [ ] Update docs
