### ISSUE TITLE
Release 4.1.0 checklist

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#713]
- [x] spatialdata release
- [x] Update copyright
- [x] Verify list of changes in CHANGES
- [x] Build code from `make dist`
- [x] Build docs from `make dist`
- [x] Make petsc-pylith tarball
- [x] Make pylith tarball
- [x] Add pyvista to PyLith installer
- [x] DOCS: Update troubleshooting

## Release announcement
- [x] Add list of contributors
- [x] List of changes (from CHANGES)
